// wordlist.js
// Veteran-themed ANSWERS list (used for daily target)
// NOTE: All entries must be EXACTLY 5 letters, A–Z only, uppercase.

console.log("wordlist.js loaded (diagnostic)");

window.ANSWERS = [
      "ABAFT","ABEAM","ABOUT","ABORT","ALICE","ALPHA","APORT","ARMED","ARMOR","ARTIE",
      "ATSEA","AVAST","AWACS","AWASH","BEACH","BELAY","BENNY","BILGE","BINGO",
      "BOSUN","BRASS","BRAVE","BREAK","BUDDY","BUNKS","CABLE","CAULK","CHIEF","CHECK",
      "CHOCK","CLASS","CLEAT","COAST","COBRA","COMMO","CONUS","CORPS","COVER","CRAFT",
      "CRATS","CYBER","DARPA","DAVIT","DELTA","DIVER","DOCKS","DRIFT","DRILL","DRONE",
      "EAGLE","ECLUB","EJECT","EXFIL","FIGHT","FIRST","FLEET","FLANK","FLOOD",
      "FORCE","FRAGO","FUBAR","GATES","GIZMO","GRIDS","GUARD","GUMBY","HATCH",
      "HELOS","HITCH","HOOCH","HONOR","HOTEL","INDIA","INFIL","JAVAS","JEEPS","KABAR",
      "KHAKI","KLICS","KNIFE","KNINE","KNOTS","KOREA","LANDS","LANCE","LEAVE","LIFER",
      "LIBBO","LINER","LUGER","MAJOR","MEDIC","MIDDY","MILES","MOTOR","MRATS","NAVAL",
      "NAVYS","NCOIC","NEWBY","NIGHT","NORTH","NOTAM","OATHS","OBEYS","OCLUB","OMESS",
      "OPCON","OPFOR","OPORD","OPSEC","OPTIC","ORBIT","ORDER","OUTDO","PACKS","PADRE",
      "PARKA","PEACE","PIECE","PILOT","PLANK","POINT","PORTS","POWER","PROUD","RADAR",
      "RACKS","RANGE","RECON","REFIT","RISKY","RIVER","ROGER","ROMEO","ROTOR","ROUGH",
      "SABRE","SALTY","SARGE","SCUBA","SEALS","SERVE","SHAVE","SHINE","SHIPS","SHORT",
      "SIGHT","SIXBY","SKATE","SKOAL","SKOSH","SLIDE","SMOKE","SNAFU","SNAKE","SONAR",
      "SPACE","STAGE","STEAM","STERN","STIFF","SWEAT","SWORD","TALON","TANGO","TEAMS",
      "TENTS","TIGHT","TRACE","TRAIN","TROOP","TRUCK","UBOAT","UNITS","UNSAT","USVET",
      "VALOR","WATCH","WATER","WAVES","WEIGH","WILCO","WINCH","WOUND"
];
      window.WORD_INFO = {
        ABAFT: "Toward the rear\nof a ship.",
        ABEAM: "At a right angle\nto a ship’s side.",
        ABOUT: "Changing direction\nor moving around.",
        ABORT: "Stop a mission\nbefore completion.",
        ALICE: "All-purpose field gear\nfor carrying equipment.",
        ALPHA: "First NATO\nphonetic alphabet letter.",
        APORT: "Toward the left side\nof a ship.",
        ARMED: "Equipped with weapons\nfor combat or defense.",
        ARMOR: "Protective equipment\nfor troops or vehicles.",
        ARTIE: "Short for artillery.\nHeavy battlefield weapons.",
        ATSEA: "Serving aboard\na ship at sea.",
        AVAST: "Old naval command\nmeaning \"stop.\"",
        AWACS: "Airborne radar aircraft\nfor command and control.",
        AWASH: "Covered by water\non deck or surface.",

        BEACH: "Landing area\nfor amphibious forces.",
        BELAY: "Cancel or ignore\na previous order.",
        BENNY: "Slang for a benefit.\nOften said sarcastically.",
        BILGE: "Lowest compartment\ninside a ship.",
        BINGO: "Minimum fuel needed\nto return safely.",
        BOSUN: "Ship’s deck supervisor\nand equipment chief.",
        BRASS: "Informal term\nfor senior officers.",
        BRAVE: "Showing courage\nin difficult situations.",
        BREAK: "Pause in radio traffic\nbetween transmissions.",
        BUDDY: "Trusted partner\nor teammate.",
        BUNKS: "Sleeping racks\nin ships or barracks.",

        CABLE: "Heavy line or chain\nused aboard ships.",
        CAULK: "Seal seams\nto prevent leaks.",
        CHIEF: "Senior enlisted leader\nin Navy or Coast Guard.",
        CHECK: "Confirm or verify\ninformation received.",
        CHOCK: "Deck fitting guiding\nrope or cable.",
        CLASS: "Group in the same\ntraining program.",
        CLEAT: "Device used\nto secure rope.",
        COAST: "Area where land\nmeets the sea.",
        COBRA: "Military attack helicopter\nor weapon system.",
        COMMO: "Short for communications\nequipment or personnel.",
        CONUS: "Continental United States.\nMilitary location term.",
        CORPS: "Large military formation\nor service branch.",
        COVER: "Provide protection\nfor another unit.",
        CRAFT: "Small boat\nor specialized vehicle.",
        CRATS: "C-Rations.\nEarly military field meals.",
        CYBER: "Digital networks\nand electronic warfare.",

        DARPA: "Defense research agency\nfor advanced technology.",
        DAVIT: "Small crane used\nto lower boats.",
        DELTA: "Fourth letter\nof NATO alphabet.",
        DIVER: "Underwater specialist\nfor repair or combat.",
        DOCKS: "Structures where ships\ntie up for service.",
        DRIFT: "Movement caused\nby wind or current.",
        DRILL: "Training exercise\nfor readiness.",
        DRONE: "Unmanned aircraft\nfor surveillance.",

        EAGLE: "Symbol of the\nUnited States.",
        ECLUB: "Enlisted social club\non military bases.",
        EJECT: "Emergency escape\nfrom an aircraft.",
        EXFIL: "Extraction from\na mission area.",

        FIGHT: "Engage in combat\nor defend a position.",
        FIRST: "Leading position\nor primary element.",
        FLEET: "Group of naval vessels\noperating together.",
        FLANK: "Side of a formation\nor defense.",
        FLOOD: "Water entering\na ship compartment.",
        FORCE: "Military strength\nor organized units.",
        FRAGO: "Fragmentary order\nupdating a mission.",
        FUBAR: "Slang for a situation\nbadly messed up.",

        GATES: "Entry points\nto a military base.",
        GIZMO: "Informal term\nfor a device.",
        GRIDS: "Map reference system\nfor navigation.",
        GUARD: "Protect or defend\na location.",
        GUMBY: "Nickname for sailors\nin foul-weather gear.",

        HATCH: "Opening or doorway\non a ship.",
        HELOS: "Helicopters used\nin operations.",
        HITCH: "Period of military service.",
        HOOCH: "Simple living quarters\nin the field.",
        HONOR: "Integrity and ethics\nin military service.",
        HOTEL: "H in the NATO\nphonetic alphabet.",

        INDIA: "I in the NATO\nphonetic alphabet.",
        INFIL: "Movement into\na mission area.",

        JAVAS: "Slang term\nfor coffee.",
        JEEPS: "Light military utility vehicles.",

        KABAR: "Famous military\ncombat knife.",
        KHAKI: "Common military\nuniform color.",
        KLICS: "Slang for kilometers\nin distance.",
        KNIFE: "Close-combat blade\nor tool.",
        KNINE: "Military working dog.",
        KNOTS: "Speed measurement\nused at sea.",
        KOREA: "Location of major\nU.S. conflict.",

        LANDS: "Come down safely\nfrom flight.",
        LANCE: "Junior Marine rank:\nLance Corporal.",
        LEAVE: "Authorized time away\nfrom duty.",
        LIFER: "Career service member.",
        LIBBO: "Slang for liberty\nor time off.",
        LINER: "Large ocean-going ship.",
        LUGER: "Historic German pistol.",

        MAJOR: "Field-grade officer rank.",
        MEDIC: "Combat medical specialist.",
        MIDDY: "Naval cadet\nor trainee officer.",
        MILES: "Distance measure\nin navigation.",
        MOTOR: "Vehicle engine\nor drive system.",
        MRATS: "Meals Ready to Eat.\nField rations.",

        NAVAL: "Related to\nnavy operations.",
        NAVYS: "Referring to\nnaval forces.",
        NCOIC: "Non-commissioned officer\nin charge.",
        NEWBY: "New arrival\nto a unit.",
        NIGHT: "Dark hours\nfor operations.",
        NORTH: "Cardinal direction\nfor navigation.",
        NOTAM: "Notice to Air Missions.\nFlight safety alert.",

        OATHS: "Promise taken\nwhen entering service.",
        OBEYS: "Following orders\nfrom leadership.",
        OCLUB: "Officers’ social club.",
        OMESS: "Officers’ dining facility.",
        OPCON: "Operational control\nof assigned forces.",
        OPFOR: "Opposing force\nin training exercises.",
        OPORD: "Operations order\nfor a mission.",
        OPSEC: "Operations security\nprotecting information.",
        OPTIC: "Sight used\nfor aiming.",
        ORBIT: "Circular path\naround a target.",
        ORDER: "Command issued\nby leadership.",
        OUTDO: "Perform better\nthan another.",

        PACKS: "Gear carried\nin the field.",
        PADRE: "Military chaplain.",
        PARKA: "Cold-weather field jacket.",
        PEACE: "Condition without war.",
        PIECE: "Individual weapon\nor equipment.",
        PILOT: "Aircraft operator.",
        PLANK: "Wood deck board\non ships.",
        POINT: "Leading position\nin patrol.",
        PORTS: "Harbors used\nby ships.",
        POWER: "Energy or strength\nin operations.",
        PROUD: "Feeling of honor\nin service.",

        RADAR: "Detects objects\nusing radio waves.",
        RACKS: "Sleeping bunks\nin barracks.",
        RANGE: "Distance to a target.",
        RECON: "Reconnaissance mission.",
        REFIT: "Repair and resupply\nfor ships.",
        RISKY: "Dangerous situation\nin operations.",
        RIVER: "Waterway used\nfor movement.",
        ROGER: "Radio term meaning\nmessage received.",
        ROMEO: "R in the NATO\nphonetic alphabet.",
        ROTOR: "Spinning blades\non helicopters.",
        ROUGH: "Difficult conditions\nin operations.",

        SABRE: "Curved cavalry sword.",
        SALTY: "Experienced service member.",
        SARGE: "Informal term\nfor sergeant.",
        SCUBA: "Underwater breathing gear.",
        SEALS: "U.S. Navy special\noperations force.",
        SERVE: "Perform duty\nfor one’s country.",
        SHAVE: "Daily grooming\nin uniform standards.",
        SHINE: "Polish boots\nor equipment.",
        SHIPS: "Naval vessels.",
        SHORT: "Near end\nof a tour.",
        SIGHT: "Aiming device\non a weapon.",
        SIXBY: "Nickname for\n6×6 cargo truck.",
        SKATE: "Avoid difficult work.",
        SKOAL: "Smokeless tobacco\nused by troops.",
        SKOSH: "Japanese slang\nfor a little.",
        SLIDE: "Move quietly\nor reposition.",
        SMOKE: "Military slang\nfor physical training.",
        SNAFU: "Situation badly\nmessed up.",
        SNAKE: "Stealthy movement\nor winding path.",
        SONAR: "Underwater detection system.",
        SPACE: "Area beyond\nEarth’s atmosphere.",
        STAGE: "Prepare equipment\nbefore operations.",
        STEAM: "Power source\nfor older ships.",
        STERN: "Rear section\nof a ship.",
        STIFF: "Hard conditions\nin training.",
        SWEAT: "Effort during\nphysical training.",
        SWORD: "Historic or ceremonial weapon.",

        TALON: "Claw of a bird\nor weapon name.",
        TANGO: "Target or enemy\nin radio slang.",
        TEAMS: "Groups working\ntoward a mission.",
        TENTS: "Temporary field shelters.",
        TIGHT: "Secure or controlled\nsituation.",
        TRACE: "Follow a path\nor signal.",
        TRAIN: "Practice skills\nfor readiness.",
        TROOP: "Individual soldier.",
        TRUCK: "Military transport vehicle.",

        UBOAT: "German submarine\nin World War II.",
        UNITS: "Military organizations\nor formations.",
        UNSAT: "Unsatisfactory result\nor performance.",
        USVET: "U.S. veteran.\nFormer service member.",

        VALOR: "Exceptional courage\nin combat.",

        WATCH: "Scheduled duty period\nstanding guard.",
        WATER: "Essential supply\nfor operations.",
        WAVES: "Women Accepted for\nVolunteer Emergency Service.",
        WEIGH: "Raise anchor\nto depart.",
        WILCO: "Radio term meaning\n\"will comply.\"",
        WINCH: "Device used\nfor lifting loads.",
        WOUND: "Injury received\nin combat."
      };cs

// IMPORTANT: Initialize VALID_WORDS with answers so every answer is always a valid guess.
window.VALID_WORDS = window.ANSWERS.slice();

console.log("ANSWERS COUNT:", window.ANSWERS.length);